name: TreasureChest
author: Mtihc
description: Place chest that adds some items everytime someone opens it for the first time.
main: com.mtihc.minecraft.treasurechest.TreasureChestPlugin
depend: []
softdepend: []
version: 6.0.3
commands:
    treasurechest:
        aliases: [tchest]
        description: Type /tchest ? for more info
        usage: /treasurechest ? or /tchest ?
permissions:
    treasurechest.set:
        description: Allows you to turn regular chests into treasure chests and set their messages. And forget time.
        default: op
    treasurechest.delete:
        description: Allows you to delete treasure chests and turn them into regular chests again.
        default: op
    treasurechest.reload:
        description: Allows you to reload the configuration files.
        default: op
    treasurechest.unlimited:
        description: Allows you to turn treasure chests into unlimited chests.
        default: op
    treasurechest.access.treasure:
        description: Allows opening treasure chests
        default: true
    treasurechest.access.unlimited:
        description: Allows opening unlimited chests
        default: op
    treasurechest.count:
        description: Allows you to count how many chests you have found
        default: op
    treasurechest.count.others:
        children:
            treasurechest.count: true
        description: Allows you to count how many chests you or someone else has found
        default: op
    treasurechest.forget:
        description: Allows you to make a chest forget that you have found it
        default: op
    treasurechest.forget.others:
        children:
            treasurechest.forget: true
        description: Allows you to make a chest forget that you or someone else has found it
        default: op
    treasurechest.forget.all:
        description: Allows you to make a chest forget that anybody has found it
        default: op
    