# 
# Configure default settings for new Treasure Chests
# 
# messages
#     The messages that are displayed when a player opens the chest
# 
# ignoreProtection
#     Whether to disable other plugins' chest protection. Like WorldGuard's region protection.
#     true: Players can access treasure chests, eventhough they are protected.
#     false: Players can't access treasure chests when they are protected
# 
defaults:
    messages:
        found: 'You have found treasure!'
        found_already: 'You have already looted this treasure...'
        unlimited: 'Take as much as you want!'
    ignoreProtection: false